package org.spring.hibernate.query;

import org.spring.hibernate.entity.EntityMetadata;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Utility class for building basic SQL statements for CRUD operations.
 * Works directly with EntityMetadata.
 */
public final class SqlBuilder {
    private SqlBuilder() {}

    /**
     * Builds a SELECT query by id column
     */
    public static String selectById(EntityMetadata metadata) {
        return "SELECT * FROM " + metadata.tableName() +
                " WHERE " + metadata.idColumn() + " = ?";
    }

    /**
     * Builds an INSERT query skipping the id column (autogenerated)
     */
    public static String insert(EntityMetadata metadata) {
        List<String> columnsList = metadata.columns().keySet().stream().filter(c -> !c.equals(metadata.idColumn())).toList();
        String sqlFieldsPart = String.join(", ", columnsList);
        String sqlFilledPart = columnsList.stream().map(c -> "?").collect(Collectors.joining(", "));
        return "INSERT INTO " + metadata.tableName() + "(" + sqlFieldsPart + ") VALUES (" + sqlFilledPart + ")";
    }

    /**
     * Builds a UPDATE query by id column
     */
    public static String updateById(EntityMetadata m) {
        var cols = m.columns().keySet().stream()
                .filter(c -> !c.equals(m.idColumn()))
                .toList();
        String set = cols.stream().map(c -> c + "=?").collect(Collectors.joining(", "));
        return "UPDATE " + m.tableName() + " SET " + set + " WHERE " + m.idColumn() + " = ?";
    }

    /**
     * Builds a DELETE query by id column
     */
    public static String deleteById(EntityMetadata metadata) {
        return "DELETE FROM " + metadata.tableName() +
                " WHERE " + metadata.idColumn() + " = ?";
    }
}
