package org.spring.hibernate.query;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.spring.hibernate.annotation.FetchType;
import org.spring.hibernate.entity.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Utility class for building basic SQL statements for CRUD operations.
 * Works directly with EntityMetadata.
 */
public final class SqlBuilder {
    private static final Logger log = LogManager.getLogger(SqlBuilder.class);

    private SqlBuilder() {
    }

    public static String selectByColumn(String table, String column) {
        return "SELECT * FROM %s WHERE %s = ?".formatted(table, column);
    }

    public static String selectByIdWithJoin(Class<?> rootClass, EntityMetadata rootMeta, Map<Class<?>, EntityMetadata> entities) {
        StringBuilder select = new StringBuilder("SELECT ");
        String from = " FROM " + rootMeta.tableName() + " t0";
        StringBuilder join = new StringBuilder();
        appendAliasedColumns(select, rootMeta, "t0");
        int tableCounter = 1;
        for (RelationField relationField : rootMeta.relationFields()) {
            if (relationField.fetchType().equals(FetchType.EAGER) && !relationField.isRelationOwner()) {
                String childAlias = "t" + tableCounter++;
                Class<?> childClass = EntityHelper.getEntityClass(relationField.field());
                EntityMetadata childMeta = entities.get(childClass);
                String foreignKey = childMeta.findForeignKeyBy(rootClass)
                        .orElseThrow(() -> new IllegalStateException("foreignKey to " + rootClass.getSimpleName() + " in " + childClass.getSimpleName() + " not found"));;
                log.trace("{}: has eager Collection<{}> -> build join sql",
                        rootMeta.tableName(),
                        childClass.getSimpleName()
                );
                select.append(", ");
                appendAliasedColumns(select, childMeta, childAlias);
                join.append(" LEFT JOIN ")
                        .append(childMeta.tableName()).append(" ").append(childAlias)
                        .append(" ON t0.").append(rootMeta.idColumn())
                        .append(" = ")
                        .append(childAlias).append(".").append(foreignKey).append(" ");
            }
        }
        String space = join.isEmpty() ? " " : "";
        String where = space + "WHERE t0." + rootMeta.idColumn() + " = ?";
        return select + from + join + where;
    }

    private static void appendAliasedColumns(StringBuilder sb, EntityMetadata meta, String tableAlias) {
        List<String> cols = new ArrayList<>();
        meta.fields().stream()
                .map(EntityHelper::getPhysicalColumnName)
                .flatMap(Optional::stream)
                .forEach(columnName -> cols.add(tableAlias + "." + columnName + " AS " + tableAlias + "_" + columnName));
        sb.append(String.join(", ", cols));
    }

    /**
     * Builds an INSERT query skipping the id column (autogenerated)
     */
    public static String insert(EntityMetadata metadata) {
        List<String> columnsList = metadata.fields().stream()
                .map(EntityHelper::getPhysicalColumnName)
                .flatMap(Optional::stream)
                .filter(c -> !c.equals(metadata.idColumn()))
                .toList();
        String sqlFieldsPart = String.join(", ", columnsList);
        String sqlFilledPart = columnsList.stream().map(c -> "?").collect(Collectors.joining(", "));
        return "INSERT INTO " + metadata.tableName() + "(" + sqlFieldsPart + ") VALUES (" + sqlFilledPart + ")";
    }

    /**
     * Builds a UPDATE query by id column
     */
    public static String updateById(EntityMetadata metadata) {
        var cols = metadata.fields().stream()
                .map(EntityHelper::getPhysicalColumnName)
                .flatMap(Optional::stream)
                .filter(c -> !c.equals(metadata.idColumn()))
                .toList();
        String set = cols.stream().map(c -> c + "=?").collect(Collectors.joining(", "));
        return "UPDATE " + metadata.tableName() + " SET " + set + " WHERE " + metadata.idColumn() + " = ?";
    }

    /**
     * Builds a DELETE query by id column
     */
    public static String deleteById(EntityMetadata metadata) {
        return "DELETE FROM " + metadata.tableName() +
                " WHERE " + metadata.idColumn() + " = ?";
    }
}
