package org.spring.hibernate.query;

import org.spring.hibernate.entity.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Utility class for building basic SQL statements for CRUD operations.
 * Works directly with EntityMetadata.
 */
public final class SqlBuilder {
    private SqlBuilder() {
    }

    public static String selectByIdWithJoin(EntityMetadata rootMeta, Map<Class<?>, EntityMetadata> entities) {
        StringBuilder select = new StringBuilder("SELECT ");
        String from = " FROM " + rootMeta.tableName() + " t0";
        StringBuilder join = new StringBuilder();
        appendAliasedColumns(select, rootMeta, "t0");
        int tableCounter = 1;
        for (EntityField entityField : rootMeta.fields()) {
            if (entityField instanceof RelationField relationField && !relationField.relation().isRelationOwner()) {
                RelationData relation = relationField.relation();
                String childAlias = "t" + tableCounter++;
                Class<?> childClass = EntityHelper.getEntityClass(relationField.field());
                EntityMetadata childMeta = entities.get(childClass);
                select.append(", ");
                appendAliasedColumns(select, childMeta, childAlias);
                join.append(" LEFT JOIN ")
                        .append(childMeta.tableName()).append(" ").append(childAlias)
                        .append(" ON t0.").append(relation.foreignKey())
                        .append(" = ")
                        .append(childAlias).append(".").append(childMeta.idColumn());
            }
        }
        String where = "WHERE t0." + rootMeta.idColumn() + " = ?";
        return select + from + join + where;
    }

    private static void appendAliasedColumns(StringBuilder sb, EntityMetadata meta, String tableAlias) {
        List<String> cols = new ArrayList<>();
        meta.fields().stream()
                .map(EntityHelper::getPhysicalColumnName)
                .flatMap(Optional::stream)
                .forEach(columnName -> cols.add(tableAlias + "." + columnName + " AS " + tableAlias + "_" + columnName));
        sb.append(String.join(", ", cols));
    }

    /**
     * Builds an INSERT query skipping the id column (autogenerated)
     */
    public static String insert(EntityMetadata metadata) {
        List<String> columnsList = metadata.fields().stream()
                .map(EntityHelper::getPhysicalColumnName)
                .flatMap(Optional::stream)
                .filter(c -> !c.equals(metadata.idColumn()))
                .toList();
        String sqlFieldsPart = String.join(", ", columnsList);
        String sqlFilledPart = columnsList.stream().map(c -> "?").collect(Collectors.joining(", "));
        return "INSERT INTO " + metadata.tableName() + "(" + sqlFieldsPart + ") VALUES (" + sqlFilledPart + ")";
    }

    /**
     * Builds a UPDATE query by id column
     */
    public static String updateById(EntityMetadata metadata) {
        var cols = metadata.fields().stream()
                .map(EntityHelper::getPhysicalColumnName)
                .flatMap(Optional::stream)
                .filter(c -> !c.equals(metadata.idColumn()))
                .toList();
        String set = cols.stream().map(c -> c + "=?").collect(Collectors.joining(", "));
        return "UPDATE " + metadata.tableName() + " SET " + set + " WHERE " + metadata.idColumn() + " = ?";
    }

    /**
     * Builds a DELETE query by id column
     */
    public static String deleteById(EntityMetadata metadata) {
        return "DELETE FROM " + metadata.tableName() +
                " WHERE " + metadata.idColumn() + " = ?";
    }
}
